//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int employee_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int role { get; set; }
        public int status { get; set; }
        public string phone { get; set; }
        public string birthday { get; set; }
        public string first_name { get; set; }
        public string type { get; set; }
        public string code { get; set; }
        public string last_name { get; set; }
    }
}
