//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_token
    {
        public int employee_token_id { get; set; }
        public int employee_id { get; set; }
        public string udid { get; set; }
        public string token { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
